repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.5.6
      hooks:
          - id: aoc-tiles
            args:
              - --auto-add-tiles-to-git=amend
              - --count_as_solved_when=on_leaderboard